export default ProductListingType = {
  TYPE: 'PRODUCTLISTING',
  REQ_SUCCESS: 'PRODUCTLISTING_FETCH_SUCCESS',
  REQ_FAILURE: 'PRODUCTLISTING_FETCH_FAILURE',
  REQ_CLEARLISTING: 'PRODUCTLISTING_CLEARLISTING',
};
